service: vital-signs

# app and org for use with dashboard.serverless.com
# app: vital-signs-app
# org: jeffspencerd

provider:
  name: aws
  runtime: python3.8
  profile: tellus
  deploymentBucket:
    name : vital-signs-monitor
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

functions:
  mon:
    handler: src/predict.lambda_handler
    package:
      include:
        - src/utils.py
        - src/config.py
        - src/predict.py
    events :
      - http : POST /monitor

plugins:
  - serverless-python-requirements
custom:
 pythonRequirements:
  slim : true
  noDeploy:
    - boto3

#   iamRoleStatements:
#     - Effect: "Allow"
#       Action:
#         - "s3:ListBucket"
#         - "s3:GetObject"
#       Resource: "arn:aws:s3:::vital-signs-monitor/model/*"
#     - Effect: "Allow"
#       Action:
#         - "s3:PutObject"
#         - "s3:PutObjectAcl"
#       Resource: "arn:aws:s3:::vital-signs-monitor/data/*"
# # you can overwrite defaults here
#  region: us-east-1
