service: vital-signs

# app and org for use with dashboard.serverless.com
app: vital-signs-app
org: jeffspencerd

provider:
  name: aws
  runtime: python3.8
  profile: tellus
  memorySize: 256
  reservedConcurrency: 200
  # disableLogs: true
  deploymentBucket:
    name : vital-signs-monitor
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:GetObjectAcl"
        - "s3:GetObjectVersion"
      Resource: "arn:aws:s3:::vital-signs-monitor/model/*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:DeleteObject"
        - "s3:DeleteObjectVersion"
      Resource: "arn:aws:s3:::vital-signs-monitor/data/*"

functions:
  mon:
    handler: src/predict.lambda_handler
    package:
      include:
        - src/utils.py
        - src/config.py
        - src/predict.py
    events :
      - http : POST /monitor

plugins:
  - serverless-python-requirements
custom:
 pythonRequirements:
  slim : true
  noDeploy:
    - boto3
